apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: ping-pong-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: voting-app-pod
    app: ping-pong-service